name: Icon
version: 1.7.0
description: Icon plugin to present Font Awesome icons set for Flextype.
icon: fab fa-font-awesome-flag
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/icon
bugs: https://github.com/flextype-plugins/icon/issues
license: MIT

dependencies:
  flextype: 0.9.15
  twig: '>=1.0.0'
